<?php
$product = $this->getValue('product');

?>

<div class="contentDivider">&nbsp;</div>
    <div class="contentLeft">
      Created by <?php echo $product['productAuthor'];?>
      <br/>
      Languages: <?php echo $product['productLanguages'];?>
    </div><!--END contentleft-->
    <div class="contentRight">

      <h3 class="contentTitle">
      <?php echo $product['productName'];?>
      </h3>
      <?php
      if (isset($product['productImage']) && $product['productImage'] != "") {
        $imgName = $product['productImage'];
        echo "<img src='images/$imgName' border='0'/>";
      }
      ?>
      <p class="contentDescription">
      <?php echo $product['productDescription'];?>
      </p>
      <p class="price">
          $<?php echo $product['productPrice'];?> (CAD)
      </p>
      <div class="clear"></div>
      <h2 class="buyNow">
          <a href="/?action=buy&product=<?php echo $product['id'];?>">Buy now</a>
      </h2>
    </div><!--END contentright-->
