<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
    
    <h3>About Me</h3>
        
        <p>
            My name is Kurtis Funai - I'm a website developer and programmer located in Ottawa, Ontario, Canada. I've always loved to build sites - creating my first even before starting high school. That passion has continued to grow throughout the years, turning my attentions towards web programming.
            <img src="images/aboutme175.jpg" class="aboutMePic"/>
        </p>
        <p>
            I'm currently enrolled at Algonquin College in Web Application Development, set to graduate in April, 2011. I spend most of my development time working with PHP, jQuery & MySQL - however throughout my education I have worked with various technologies and platforms such as ASP.NET &amp; C#, which have helped to shape me as a developer.
        </p>
        <p>
          My goals are to become a contributing member of the open source community, and to pay forward the knowledge and education that I have received thus far.
        </p>
        
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>