<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
    <h3>About Me - Web Application Developer from Ottawa, Ontario</h3>
        <p class="contentDescription">
        My name is Kurtis Funai - I'm a website developer and programmer located in Ottawa, Ontario, Canada. Web design has always been a passion of mine, creating my first sites before even starting high school. My goal is to become a contributing member of the open source community, and to pay forward the knowledge and education that I have received thus far.
        </p>
        <h4>Skills</h4>
        <p>PHP, JavaScript, XHTML, CSS</p>

        Adobe Photoshop, Flash & Illustrator
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>