<?php include("HeaderTemplate.phtml"); ?>


<div id="content">
     <h3>Purchase</h3>
     <?php
     if (isset($_SESSION['updateCartError'])) {
         echo "<p class='errorText'>";
         foreach ($_SESSION['updateCartError'] as $key=>$error){
            echo $error."<br/>";
         }
         unset($_SESSION['updateCartError']);
         echo '</p>';
     }
     ?>
     <?php
     $cart = $this->getValue('cart');
     if (!empty($cart)) {
     ?>
         <form name="cartForm" method="post" action="?action=updateCart">
         <?php
            $totalPrice = 0;
            $itemPrice = 0;
             foreach ($cart as $items=>$item) {
                 $itemPrice = $item['productInfo']['productPrice'];
                 $itemPrice = $itemPrice*$item['quantity'];
                 echo '<div class="cartItem">';
                 echo '<div class="contentLeft"><h3>'.$item['productInfo']['productName'].'</h3></div>';
                 echo '<div class="contentRight"><p><strong>Description</strong>: <br/>'.$item['productInfo']['productDescription'].'</p>';
                 echo '<div class="priceAndQuantity">';
                 echo '<p><strong>Price</strong>: $'.$item['productInfo']['productPrice'].'</p>';
                 echo '<p><strong>Quantity</strong>: <input type="text" name="quantities['.$item['id'].']" value="'.$item['quantity'].'" size="4" maxlength="2"/></p>';
                 echo '<p><a href="?action=removeFromCart&product='.$item['id'].'">Remove Item</a></p>';
                 echo '</div>';
                 echo '</div></div>';
                 $totalPrice += $itemPrice;
             }
         ?>
             <div class="contentLeft">&nbsp;</div>
             <div class="contentRight">
                 
                 <div class="checkoutButtons">
                     <input type="submit" value="Update Cart"/>
                     <p style="float:right;"><?php echo "<strong>Total</strong>: $";echo sprintf("%01.2f", $totalPrice);?></p>
                     <div class="clear"></div>
                    <a href="?action=checkout">Checkout</a>
                 </div>
             </div>
         </form>
     <?php
     }
     else {
         echo "You have no items in your cart";
     }
     ?>



</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>