<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
     <h3>Contact Me</h3>
     <p class="contentDescription">
              Ut sollicitudin tempor placerat. Nunc fringilla viverra purus quis pellentesque. Suspendisse pulvinar nisl pulvinar velit pretium ornare. Phasellus vitae tristique urna. Etiam sit amet dignissim elit. Duis nunc diam, suscipit vel porttitor non, ornare at ligula. Sed ut quam leo. Vivamus accumsan gravida posuere. Mauris vel nisl sapien, vitae egestas mi. Aliquam facilisis ipsum a dui elementum interdum. Donec eros libero, dignissim ac semper nec, condimentum vitae nulla. Nulla volutpat tempus odio non ultricies. Proin sagittis ullamcorper euismod. Aliquam consequat magna a libero aliquet a pulvinar tortor iaculis.
     </p>

         
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>