</div><!--END contentwrapper--></div>

    <div id="footerWrapper">
    	<div id="footer""> <br/>
         <div id="footerLeft"><a href="mailto:me@kurtfunai.com">me@kurtfunai.com</a><br/><br/>
             1+ (613) 899-5358<br/><br/>
             Ottawa, Ontario, Canada</div><!--END FOOTERLEFT-->
         <div id="footerRight">
         		<ul class="socialList">
            	<li><a href="http://twitter.com/#!/kurtisfunai" target="_blank"><img src="images/Twitter-icon.png" border="0"/><span class="socialText">Follow me on Twitter</span></a></li>
              <li><img src="images/FaceBook-icon.png" border="0"/><span class="socialText">Be a fan on Facebook</span></li>
            </ul>
         </div><!--END FOOTERRIGHT-->
         <span class="copyright">&copy; kurtis funai 2011</span>
       </div>
    </div><!--END FOOTER-->

  </div><!--END CONTENTWRAPPER-->
</div><!--END BANNERWRAPPER-->
</body>
</html>
