<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Kurt Funai.com</title>
<link rel="stylesheet" type="text/css" href="css/global.css" />
<script type="text/javascript" src="js/jquery-1.5.min.js" ></script>
</head>

<body>
<div id="bannerwrapper">
	<div id="sitewrapper">
  	<div id="banner">
    	<a href="index.php"><span class="bannerTitle">Kurt Funai.com</span></a>
    	<ul class="bannerLinks">
      	<li><a href="?action=products">PRODUCTS</a></li>
        <li><a href="?action=about">ABOUT</a></li>
        <!--<li><a href="?action=hire">HIRE</a></li>-->
        <li><a href="?action=contact">CONTACT</a></li>
      </ul>

    </div><!--END BANNER-->

    <div id="contentwrapper">