<?php include("HeaderTemplate.phtml"); ?>
<script type="text/javascript">
function clearField(field) {
  if (field.value==field.defaultValue)
	{
		field.value = "";
	}
}

function populateField(field) {
  if (field.value=="")
	{
		field.value = field.defaultValue;
	}
}

function removeDefaults() {
  //make this function ambiguous some day - see below
  if ($("#contactName").val() == "Name...") {
      $("#contactName").val('');
  }
  if ($("#contactInfo").val() == "Email or phone number...") {
      $("#contactInfo").val('');
  }
  if ($("#contactDescription").val() == "Let me know how I can help...") {
      $("#contactDescription").val('');
  }
  
  /*
  var formElements = new Array("contactName", "contactInfo", "contactDescription");
  alert($("#"+formElements[0]).val());for(var i = 0; i < formElements.length; i++){
      if (formElements[i].value == formElements[i].defaultValue)
        {
            alert(formElements[i].value)// = "";
        }
  }*/
}

$(document).ready(function() {
        // get this working
        $("#fieldSet").focus();
});
</script>

<div id="content">
     <h3>Hire me</h3>
        <?php
        if ($this->_form->hasErrors()) {
            $errors = $this->_form->getErrorMessages();
            echo "<p class='errorText'>";
            foreach ($errors as $key=>$value){
                echo "<br/>".$value;
            }
            echo "</p>";
        }

        
        if (isset($_SESSION['sentConfirmation'])) {
            echo "<p class='successText'>".$_SESSION['sentConfirmation']."</p>";
            unset($_SESSION['sentConfirmation']);
        }

        
        ?>

        
        <form action="" name="hireForm" id="hireForm" onsubmit="return removeDefaults();" method="post">
            <fieldset id="fieldSet" class="weee">
                    <input type="text" name="contactName" id="contactName" size="40" onfocus="clearField(this);" onblur="populateField(this);" value="<?php $this->_form->repopulateForm('contactName', 'Name...') ?>" />
            
                    <input type="text" name="contactInfo" id="contactInfo" size="40" onfocus="clearField(this);"  onblur="populateField(this);" value="<?php $this->_form->repopulateForm('contactInfo', 'Email or phone number...') ?>" />
            
            		<textarea name="contactDescription" id="contactDescription" rows="6" cols="52" onfocus="clearField(this);"  onblur="populateField(this);" ><?php $this->_form->repopulateForm('contactDescription', 'Let me know how I can help...') ?></textarea>
            </fieldset>
            <input type="submit" name="submit" class="submit" value="Send"/>
        </form>


         
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>