<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
    
    <h3>Welcome to KurtFunai.com</h3>
        
        <p>
        I've created site to showcase and sell my web applications, as well as offer my services for sale as a web developer.
        </p>
        <p>
            If you'd like you know a bit about me, you can head over to my <a href="?action=about">about me page</a>.<br/><br/>
            If you're more interested in finding out about the services I offer or the useful web applications I sell,
            head over to my <a href="?action=products">products page</a>. There you will find a list of my products,
            and a description of how they can improve your websites functionality. I also offer bundles, which are
            blocks of my development time, along with my ImageUploader (free and installed) on your website!
            
        </p>

        
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>