<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
    <img src="images/whatsnew.png" class='center'/>
            <div class="contentleft">
              Created by <?php echo $this->getValue('featured_productAuthor');?>
              <br/>
              Languages: <?php echo $this->getValue('featured_productLanguages');?>
            </div><!--END contentleft-->
            <div class="contentright">

              <h3 class="contentTitle">
              <?php echo $this->getValue('featured_productName');?>
              </h3>

              <img src="images/<?php echo $this->getValue('featured_productImage');?>" border="0"/>

              <p class="contentDescription">
              <?php echo $this->getValue('featured_productDescription');?>
              </p>
              <p class="price">
                  $<?php echo $this->getValue('featured_productPrice');?> (CAD)
              </p>
              <div class="clear"></div>
              <h2 class="buyNow">
                  <a href="/?action=buy&product=<?php echo $this->getValue('featured_id');?>">Buy now</a>
              </h2>
            </div><!--END contentright-->
    <div class="contentDivider">&nbsp;</div>
    <?php var_dump($this->getValue('nonFeatured'));
        $nonFeatured = $this->getValue('nonFeatured');
        foreach ($nonFeatured as $product=>$results) {
            echo '<br/>';
            foreach ($results as $key=>$value) {
                echo $value.'<br/>';
                //check type, create appropriate view, pass values
            }
        }
    ?>
   
         
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>