<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
      	<img src="images/whatsnew.png" class='center'/>
                <div id="contentleft">
                  Created by Kurtis Funai<br/>
                  Languages: php, javascript
                </div><!--END contentleft-->
                <div id="contentright">
                  <h3 class="contentTitle">Image Uploader</h3>
                  <img src="images/imageuploader.jpg" border="0"/>
                  <p class="contentDescription">
                  Ut sollicitudin tempor placerat. Nunc fringilla viverra purus quis pellentesque. Suspendisse pulvinar nisl pulvinar velit pretium ornare. Phasellus vitae tristique urna. Etiam sit amet dignissim elit. Duis nunc diam, suscipit vel porttitor non, ornare at ligula. Sed ut quam leo. Vivamus accumsan gravida posuere. Mauris vel nisl sapien, vitae egestas mi. Aliquam facilisis ipsum a dui elementum interdum. Donec eros libero, dignissim ac semper nec, condimentum vitae nulla. Nulla volutpat tempus odio non ultricies. Proin sagittis ullamcorper euismod. Aliquam consequat magna a libero aliquet a pulvinar tortor iaculis.
                  </p>
                  <h2 class="buyNow"><a href="/?action=buy&product=1">Buy now</a></h2>
                </div><!--END contentright-->
      	<div class="contentDivider">&nbsp;</div>
         <p class="contentDescription">
                  Ut sollicitudin tempor placerat. Nunc fringilla viverra purus quis pellentesque. Suspendisse pulvinar nisl pulvinar velit pretium ornare. Phasellus vitae tristique urna. Etiam sit amet dignissim elit. Duis nunc diam, suscipit vel porttitor non, ornare at ligula. Sed ut quam leo. Vivamus accumsan gravida posuere. Mauris vel nisl sapien, vitae egestas mi. Aliquam facilisis ipsum a dui elementum interdum. Donec eros libero, dignissim ac semper nec, condimentum vitae nulla. Nulla volutpat tempus odio non ultricies. Proin sagittis ullamcorper euismod. Aliquam consequat magna a libero aliquet a pulvinar tortor iaculis.
         </p>
         
</div><!--END CONTENT-->

<?php include("FooterTemplate.phtml"); ?>