<?php include("HeaderTemplate.phtml"); ?>

<div id="content">
    <img src="images/whatsnew.png" class='center'/>
            <div class="contentLeft">
              Created by <?php echo $this->getValue('featured_productAuthor');?>
              <br/>
              Languages: <?php echo $this->getValue('featured_productLanguages');?>
            </div><!--END contentleft-->
            <div class="contentRight">

              <h3 class="contentTitle">
              <?php echo $this->getValue('featured_productName');?>
              </h3>

              <img src="images/<?php echo $this->getValue('featured_productImage');?>" border="0"/>

              <p class="contentDescription">
              <?php echo $this->getValue('featured_productDescription');?>
              </p>
              <p class="price">
                  $<?php echo $this->getValue('featured_productPrice');?> (CAD)
              </p>
              <div class="clear"></div>
              <h2 class="buyNow">
                  <a href="?action=buy&product=<?php echo $this->getValue('featured_id');?>">Buy now</a>
              </h2>
            </div><!--END contentright-->
    
    <?php //var_dump($this->getValue('nonFeatured'));
        $nonFeatured = $this->getValue('nonFeatured');
        
        foreach ($nonFeatured as $products=>$product) {
            if ($product['productType'] == 'bundle'){
                //require_once 'Kurt/View.php';
                //$bundleView = new View(APPLICATION_PATH."/Templates/ProductTemplates/BundleTemplate.phtml");
                $this->setTemplateFile(APPLICATION_PATH."/Templates/ProductTemplates/BundleTemplate.phtml");
                $this->setValue('product',$product);
                echo $this->render();
            }
            elseif ($product['productType'] == 'app') {

            }
            else {
                echo 'There is a missing product type.<br/>';
            }
        }
    ?>
   
         
</div><!--END CONTENT-->
<div class="clear"></div>
<?php include("FooterTemplate.phtml"); ?>